### ISSUE TITLE
这个Demo运行不起来

### ISSUE THREAD

**Issue by arden** [rhcad/vgplay-ios#1]
Ld /Users/arden/Library/Developer/Xcode/DerivedData/TestView-exyxektiuthhyrcqkqlyjobctyyl/Build/Products/Debug-iphoneos/TestVGPlay.app/TestVGPlay normal armv7
    cd /Users/arden/data/source/swift/Bezier/vgplay-ios/TestView
    export IPHONEOS_DEPLOYMENT_TARGET=7.0
    export PATH="/Users/arden/Desktop/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/usr/bin:/Users/arden/Desktop/Xcode.app/Contents/Developer/usr/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"
    /Users/arden/Desktop/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++ -arch armv7 -isysroot /Users/arden/Desktop/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS9.3.sdk -L/Users/arden/Library/Developer/Xcode/DerivedData/TestView-exyxektiuthhyrcqkqlyjobctyyl/Build/Products/Debug-iphoneos -F/Users/arden/Library/Developer/Xcode/DerivedData/TestView-exyxektiuthhyrcqkqlyjobctyyl/Build/Products/Debug-iphoneos -filelist /Users/arden/Library/Developer/Xcode/DerivedData/TestView-exyxektiuthhyrcqkqlyjobctyyl/Build/Intermediates/TestView.build/Debug-iphoneos/TestView.build/Objects-normal/armv7/TestVGPlay.LinkFileList -miphoneos-version-min=7.0 -dead_strip -Xlinker -no_deduplicate -fembed-bitcode-marker -ObjC -lTouchVG -lTouchVGCore -framework CoreGraphics -framework Foundation -framework QuartzCore -framework UIKit -stdlib=libc++ -fobjc-arc -fobjc-link-runtime -lTouchVGPlay -framework UIKit -framework QuartzCore -framework CoreGraphics -framework Foundation -lPods -Xlinker -dependency_info -Xlinker /Users/arden/Library/Developer/Xcode/DerivedData/TestView-exyxektiuthhyrcqkqlyjobctyyl/Build/Intermediates/TestView.build/Debug-iphoneos/TestView.build/Objects-normal/armv7/TestVGPlay_dependency_info.dat -o /Users/arden/Library/Developer/Xcode/DerivedData/TestView-exyxektiuthhyrcqkqlyjobctyyl/Build/Products/Debug-iphoneos/TestVGPlay.app/TestVGPlay

ld: library not found for -lTouchVGPlay
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by rhcad** [comment]
请使用 vgplay
